optimize some code
openstack4j/openstack4j pull request #92
Opened 2020-10-28 11:32 UTC by bboyHan

#91 fixed it.

I have done an in-depth reading of the source code of this framework, and feel that it is well written. Therefore, I also hope to join your team to develop and extend functions. can I ？

2020-10-30 11:18 UTC, olivergondza commented
@bboyHan, thanks for doing this.

I am about to initiate a project to clean up the codebase as this fits in just right: https://github.com/openstack4j/openstack4j/projects/1

2020-10-30 11:21 UTC, olivergondza commented on core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPort.java
> +					fixedIP.getSubnetId().equals(subnetId) &&
Nice catch. This can be made even simpler by using `Object#equals`.

2020-10-30 11:21 UTC, olivergondza commented on core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPort.java
> +					allowedAddress.getIpAddress().equals(ipAddress) &&
Same as above.

2020-10-30 11:22 UTC, olivergondza requested changes
I have added some review comments. The rest looks quite good. Please address those, and this can be merged.

2020-10-31 03:10 UTC, bboyHan reviewed
Thanks for your reply! 
Should I need to delete the other codes that you didn't added comments?

2020-10-31 12:34 UTC, olivergondza commented
@bboyHan, Parts I have not commented on are ok. Please fix what I have commented on.

2020-11-02 19:41 UTC, olivergondza commented
Please resolve conflicts sothis can be merged.

2020-11-03 12:48 UTC, closed without merging